### ISSUE TITLE
kha.compile do not compile the html5, it compile debug-html5 instead

### ISSUE THREAD

**Issue by wighawag** [KTXSoftware/vscode-kha#2]
While it was probably changed in purpose, the original intent to add a kha.compile option was to be able to use a external browser with the html5 target (non debug) and a kha --server running in the background.

kha.compile now use "debug-html5" : https://github.com/KTXSoftware/vscode-kha/blob/master/extension.js#L28

Could we have that html5 compile option back as it allow to test the game in its real context. This also allow to use feature present in some web browser like (live javascript code reload).

**Comment by RobDangerous** [comment]
Not like this, sorry. Want to add a proper tab with a target system selection.

**Comment by wighawag** [comment]
Ok, if that selection include a html5 target with compilation only, I ll be fine :)
